apiVersion: v1
items:
- apiVersion: v1
  kind: ClusterRole
  metadata:
    name: enmasse-namespace-admin
  rules:
  - apiGroups:
    - authentication.k8s.io
    - rbac.authorization.k8s.io
    - authorization.k8s.io
    resources:
    - tokenreviews
    - rolebindings
    - roles
    - localsubjectaccessreviews
    verbs:
    - create
  - apiGroups:
    - ''
    - authorization.openshift.io
    - extensions
    - route.openshift.io
    resources:
    - namespaces
    - rolebindings
    - policybindings
    - pods
    - configmaps
    - deployments
    - replicasets
    - routes
    - events
    - secrets
    - services
    - persistentvolumeclaims
    - serviceaccounts
    verbs:
    - get
    - list
    - create
    - delete
    - update
    - watch
    - patch
- apiVersion: v1
  kind: ClusterRole
  metadata:
    name: enmasse-infra-view
  rules:
  - apiGroups:
    - ''
    - extensions
    resources:
    - pods
    - configmaps
    - deployments
    verbs:
    - list
    - get
    - watch
- apiVersion: v1
  kind: ClusterRole
  metadata:
    name: enmasse-addressspace-admin
  rules:
  - resources:
    - configmaps
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- apiVersion: v1
  kind: ClusterRole
  metadata:
    name: enmasse-address-admin
  rules:
  - apiGroups:
    - ''
    resources:
    - configmaps
    - events
    verbs:
    - create
    - delete
    - list
    - get
    - watch
    - update
    - patch
kind: List
