language: java
notifications:
  email: false
  irc:
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    channels:
    - chat.freenode.net#enmasse
    use_notice: true
    skip_join: true
sudo: required
services:
- docker
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
jdk:
- oraclejdk8
before_script:
- "./systemtests/scripts/install_openshift.sh /tmp/openshift"
- "./systemtests/scripts/start_openshift.sh /tmp/openshift"
script:
- export TAG=${TRAVIS_TAG:-latest}
- export VERSION=${TRAVIS_TAG:-latest}
- "./gradlew build -i"
- "./gradlew pack buildImage tagImage pushImage"
- "./systemtests/scripts/run_test_component.sh templates/install /tmp/openshift systemtests"
- "curl -s ${SCRIPTS}/generate-bintray-descriptor.sh | bash /dev/stdin enmasse templates/build/enmasse-${TAG}.tgz > .bintray.json"
after_failure:
- "./systemtests/scripts/print_logs.sh /tmp/openshift"
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  ./gradlew tagVersion pushVersion; fi
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - SCRIPTS=https://raw.githubusercontent.com/EnMasseProject/travis-scripts/master
  - secure: x+tvxuIjSuZKLO4iO+/kqMb6RUqU7phvjV1RRQNXmAWqIBTq0cxtA4TyadUhlPazUDZLNKGEXW4EHTr7f2YwKefWKQHyZ6FhQcdb8lv8M9GAxDzRtalDh+/tip2yyZgBDakQwDytH0Dsiuh+kFuvIGCBagLesDNaMWxM7jc0E/qFNfrmJDu+jYw5SkwMzAqGeXIcWHE5Ry0iDqMz3k9A/L4vfJaKYK8axV/TJhVqCQu+L5ZLb091nj8VKigSZ89kukn14y4WhKdcf0rc1eS8fbrXrw6Vq9TXszSUVDv6lrT5ehHPVRCh2LQLpuT66hbQM/2mvysMcbWM1QH8shbUZbaCXKCB7GAfwlEkbzVQ0nBNvX7GJ32yzxRKNxr5X9O7UG9uKEC/nO3xjXp6yaFlBwC6ymAa5uwvGL6GjC5Kt5WRvrMFUncRwfEFGs3yTWSu7O5plY3KEYt0vV0quaqEZ+m7s++j6v1FxFv3izzC9IlrsJWPGxe+9ZFUkgaYkDqs6bMqXnLIQ7GF6KvWMETiXnCBdCZH68Up76oIybqmPH9kzUINi2fy1amI28oOlEi3neFncYAojzW4l7eRk7p0xGwTAucsEfUl+MsK+xiw03wquAWCuvMp8exga2ophaTZLYC2Pv+LEt4TP/clzmbTxV8qi2jQ9LBwA3R2CAdfz+s=
  - secure: lnT2MgoFqYw2ewqspLwSzFQ0HqbbBa5nGGctlg8YaaYYY/J1aS5QO3054mjCdCMKygIgFndbiFGhbUIjEpjcFBUjEQraZ70VRnx6kKSU5RehNVhgRu+fXpZ3HCZttxsXJ8a8APN9l7hvsdLNYdkRrOmqojMPGRA36kpSn46Zb6i0jUJt+sRUAeXrCeIznGgSOhpkPUE9xgBIvbQM2adQmrKDmaCwImagyGN1sC8TmOCBTJHJ3imaS3EhZ9koVFvrbBws/oAj/3jYsl3JV1GyuxVHJQD0KLDekMXp5rvOsaclPLUR1SJzqL5Lf+e4YJM+/XCRHK+FUTq60+YX+6FlyQDU5E2671r5DgZwwLYypOBN8YffUBHY7K0n71rrkAghlvdpob30H3Lxh7r40hzwY4Jvu2gFn9JJUgvPOvw5R85y4Jeb3OqmhQu+k96hNB8JvoC0ow6RCSPCOlhovh2S1mEljL8i/etJNmdFqsumoVK/0BUB1iKgR93WOFUyjMjMW1Jdg7KQ4JvDLW01zmzQZ53Y4V720BeYFLITtuL+VTdRWEuR+NlrqDSnb6QGWU6xTiaDwzacn+7RdNwCMlf9FzKryn2uttVWescPgDZlIYQ/vbimZSIboBA+2fjbqJeCiP0Unkvq45Jibw4bbdZ5uqOqMRCddc4B/0Xp04VpKF8=
  - secure: kXUbI3I1Y5+gRS3kDQDtzv/gzIPnGaGy/4WrMR0isCFAoojiXiXjvgo7jwluApvrwVexN4sEGXseRN0eCV/Iha3di/JnDmSC76QM/KnZKcoOCf6MXjaMd+Hpe7hESRsHGrcjmpzELvpXKKiicz5GfLGA8kPCvuK42/6McZGhPKQOA6Q62KH5tw4sqM6XYA8hiqGQc8Av99mUjGwWJyI5XX0VNpcmQTz4JHYkIDZFAYArXUZ+uwo6l7JvyYxp1mup/ooAX14NEt5nhaJY/1CzIHsQdlNxvCsvqp+qgctfjAOyAMh6I5klInEKu+GZVHA8cIu630MNP7O/qHTQMZ78i28EiFhkG2POTATz3gAmpoVTyk7l77NSGDpCYOVB5WbkCq3yUNO6c6xblyhkOsJOwJCdtE8BfzCbL/sacqM6LU8qTRxadUvdMYRA9M+Ag+yBfYMivkJNp6NlSXH6S6K/XnCUIH80T/4dZQ3Zm7LlmL7Iia2FH6AOic8U7s+WdVMzvK3AOcpqfKDoR+usl3UQKqdNy4LVNGhhuyJWgEJ12NgXEGdPubntssSfN3cdGWLeEUrV48hPoLY+bf89lcacmlttq867c5XWuUUABuhM+cwmuJ8+mu83QhWzS/vdc0H1xT1pKpLpO3Gs7/vo/PZSP3t/hRC6+WNARX/6NbCpbsE=
  - secure: b0itSkfj0fvBPAhQW3Is1AJX1XRnEOWCcGBP2aY81Fk0l4gpVFjrNXnQeoH6Wqcrz0B9kdOs/TjjcGfTEnu3UABAdN4pHEp3c/SL3WrlEfcfoLax4T4ul2Ms6Elr8Zx7pRNuPGClpquHhx+pJyJ3/Q+TKs2PdeIP3KnPJYZpy/Ui+8qpdkVY9hrdN4yLKv3CV+AnTjAFu+Ss9B51kVPrXwTNDDaYZtON+HawVpFIvEzfkIOfiwK5+lb5Wc70jU4MKIFXZDoZVVYpq7cbOm/kWpAyfZ4iwf9f5pAknwIK8H+mTG2h3iaG4Xv1WSal7lqRt19aEdOuAjdt4xJ8y7cln8v+csJ9M6Ok1eR3lzBfDCxQTcwOXFmW41fbSw3fCKBZLPXhp044qtRjawkmKZFkU3y3IdLEWOY0xudCRNGN9tq4JXwDppyhrTredojSbVSolAwhArSvzVzksplQZPm5az8OvnhXxF5O9+kY60wcFzLeTS+09PV69iBeDLESoDHcF4z6FUUL1/53SvSgUsXGb3HYdg6JFnLi1ZafHtdionBy9akak14i2PTeHXJmvVZFQ7E5np0pe0lHD7oMqfwPOEuHWvcJmAUDvpv9sIkzyaDCJckZpJ9Te7/gDjopFIlUU4hn0IueMKZA7t26dAy7fpLC/yKnTsja4mzLRYiSgbs=
  - secure: zLrlUuwrS9HF+K+tlqayyPR54EMwFNxGI3BwF8Yp2LNYdCY5St7o22Q7qKknRknRlMY6sZyXc3sVhCYhR3JzwamHdFNHvPmYQFRsAb56h2udM7pr/hPr5gIT7bCYDnqCtfgpbVy2ldgKife3T/3z5Auh/n+q3lH0x+lgKx2sPP/2dXAB+tFZUTHRRIF5XCHU67VIzKDWeTzQG47FY18cw0ds3b27u0+A3u735PVe+ukqNpbHyETw8+wE4WH7cXi2H7pcCwjyB26zBtsJLy4oj0XO/fUZhycfNjnYafDC/mvWXRJR3x5pNM6OnUIvTxczQcKN/9B65C/yti0iRZFoK2nzN7R/8mCJav2OhIzKlBem6XIiBY7/iuq+0FQyMgccsygv1ZSLxVe7P37ouaumatv99YTDmknyGLGJxi1QCGNZdc8L11ZZkSYW9reeuf53wTyQnfqnLJUAWi0hWYVcL5gHQXxYkaUXke4Nenv+NxOLbJZiZQOcjY3RL12UsbmGoJSmPfXmWQrh3R3r3pdpkFwdwpxrfOAP5EIn8U+hRj4aG11JHzy5Y4tpiTilIyA6/UjlN65wciv3dH8hfcC2SoYvKGfC2/EatRQowXrmQhaoKydjJUStWN/XN+BIE+kGWpygvj3x+jgloLWnATmNW7eSbPACU9GkA2NMH9nmtME=
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: HepZcALZznJ9XL1gumw4EqtG2doiWX+dEdUy0Qug+DcFM6mTb7m61YIrYmiw0h2FCqzozsSjlDjKfBLUgnUalj6f6LZCQKqThh04VKQoBmDJbUoOX7nSiaGeV9SJ18zeG8MrIkoHriJVGnfKUTL870RSQGzRvCXOUyQdx9gy/kfFFM4R9eUN8XOH/nMdmMhtoqwlhfjcY8T0qeKlCISqFCXlan+uIV7KERVSiiBdK4L4fsA5VB8Dd3SUHKe2zpcntowsBXfGI9wemWe++FysZ4Wsg+bBohiZ11A2xeHWCpswosvUHl8OcRyQDK5RqLsphdhTcFxaKvuyXl8v0eecg4ktdHkVQ0EbEauTtd/19lDa4oNpv/Thm3ElKpM77xq4gf0CLW/QNCO6OSQ9zPKughyaH3b/lseLWvVxYEKsPanRdYCZO0PjVOUGtbUpPRxP5CkNDEkW7mpfbK0IgxAemGy0mcTnSWFKQOgdB9iyiZA+lrHdrF9pc1rj5QPbDE8e7mn7FoosPsZuwGjZAb/7lBdZ4aerUXHHsBoyRrVEMvj1qABv9UJtokgo3rBoY/JGdHX9Rq9gsVVQeLLFir5EIFlsTXoaj4z+NvwC5ODklNdBoQvkXYzZ6z9OYsCGDjl09rFi7AbMXCM7nLeKzUv3XQbuEr9iHHpkWhKO8gc8hNw=
    file: "templates/build/enmasse-${TAG}.tar.gz"
    on:
      tags: true
      repo: EnMasseProject/enmasse
  
  - provider: bintray
    file: ".bintray.json"
    user: "${BINTRAY_API_USER}"
    on:
      tags: true
    key:
      secure: wFYqVs8DrJLqKrKsR1xaalhJV4P2EOo6tOAiC9LQJ6MbUabg45BKKlsvCq+w0uZkTg/mldS6NvVwFKHuvvV2RBKQKUJmbgBfrjU02WgAKwe18CsVbRuWZF2mnMbw8b9XMTFE5QtIMO+N0I4mdq5SvZwV6obvaZeDc5OK19dkANNvSPJoJx/CElUB5AKLX2lRK52t9FEHHz4FqevjQP1TVDfN8IpTIjmO6Y/icREeLWyi7C31h61wA4MBei9qxhHTfRgEYd7HUJdVK9rNaYcx3JWwXgfNRStKEuntKYI2JUwuGGf9yoAbnGNCckRDh6KkRP2NwE+8j5B/u2MRpH/xgl7kGuv+FZi3eLHGQFWx8TTEmE4uJfPM85Tt5mUbXh2HgxkWNHvuwo5HGKT6tNZ1HePdHFqonUa3Yx0a2DKQC/i7S9Rof3ywkFlzb0rVBin/k/OBGNFF7Si4ek0TYu/s7nZy5wSyViddE/1yo5NHgC3ItD/ALntwi2NQtS6bwK/fmERo2KuS/ixjjTZ+rUXTc4vkIdaNOPvrJD/y0qPNaXkeh6xDEoomoL6YkGNkxBctEjAiQTOhXg+Obev5l3yruIUSDAzm2yJQ2c1mjVeH+DK8lK7nHkb6wecv6UoI0iRUwUDOnFFsiu3mm7fFamR5v0u6b+iFA1DQNKyC89q+Dmw=
  - provider: bintray
    file: ".bintray.json"
    user: "${BINTRAY_API_USER}"
    key:
      secure: wFYqVs8DrJLqKrKsR1xaalhJV4P2EOo6tOAiC9LQJ6MbUabg45BKKlsvCq+w0uZkTg/mldS6NvVwFKHuvvV2RBKQKUJmbgBfrjU02WgAKwe18CsVbRuWZF2mnMbw8b9XMTFE5QtIMO+N0I4mdq5SvZwV6obvaZeDc5OK19dkANNvSPJoJx/CElUB5AKLX2lRK52t9FEHHz4FqevjQP1TVDfN8IpTIjmO6Y/icREeLWyi7C31h61wA4MBei9qxhHTfRgEYd7HUJdVK9rNaYcx3JWwXgfNRStKEuntKYI2JUwuGGf9yoAbnGNCckRDh6KkRP2NwE+8j5B/u2MRpH/xgl7kGuv+FZi3eLHGQFWx8TTEmE4uJfPM85Tt5mUbXh2HgxkWNHvuwo5HGKT6tNZ1HePdHFqonUa3Yx0a2DKQC/i7S9Rof3ywkFlzb0rVBin/k/OBGNFF7Si4ek0TYu/s7nZy5wSyViddE/1yo5NHgC3ItD/ALntwi2NQtS6bwK/fmERo2KuS/ixjjTZ+rUXTc4vkIdaNOPvrJD/y0qPNaXkeh6xDEoomoL6YkGNkxBctEjAiQTOhXg+Obev5l3yruIUSDAzm2yJQ2c1mjVeH+DK8lK7nHkb6wecv6UoI0iRUwUDOnFFsiu3mm7fFamR5v0u6b+iFA1DQNKyC89q+Dmw=
