#!/bin/sh

#BINTRAY_DIR = releases | snapshots
curl -T address-controller/target/address-controller.jar -u ${BINTRAY_USER}:${BINTRAY_PASSWORD} -H "X-Bintray-Package:enmasse" -H "X-Bintray-Version:${VERSION}" -H "X-Bintray-Publish: 1" -H "X-Bintray-Override: 1" https://api.bintray.com/content/enmasse/${BINTRAY_DIR}/
curl -T artemis/build/artemis-image.tar -u ${BINTRAY_USER}:${BINTRAY_PASSWORD} -H "X-Bintray-Package:enmasse" -H "X-Bintray-Version:${VERSION}" -H "X-Bintray-Publish: 1" -H "X-Bintray-Override: 1" https://api.bintray.com/content/enmasse/${BINTRAY_DIR}/
curl -T configserv/target/configserv.jar -u ${BINTRAY_USER}:${BINTRAY_PASSWORD} -H "X-Bintray-Package:enmasse" -H "X-Bintray-Version:${VERSION}" -H "X-Bintray-Publish: 1" -H "X-Bintray-Override: 1" https://api.bintray.com/content/enmasse/${BINTRAY_DIR}/
curl -T agent/build/agent.tgz -u ${BINTRAY_USER}:${BINTRAY_PASSWORD} -H "X-Bintray-Package:enmasse" -H "X-Bintray-Version:${VERSION}" -H "X-Bintray-Publish: 1" -H "X-Bintray-Override: 1" https://api.bintray.com/content/enmasse/${BINTRAY_DIR}/
curl -T keycloak/assembly/target/keycloak-bin.tar.gz -u ${BINTRAY_USER}:${BINTRAY_PASSWORD} -H "X-Bintray-Package:enmasse" -H "X-Bintray-Version:${VERSION}" -H "X-Bintray-Publish: 1" -H "X-Bintray-Override: 1" https://api.bintray.com/content/enmasse/${BINTRAY_DIR}/
curl -T keycloak-controller/target/keycloak-controller.jar -u ${BINTRAY_USER}:${BINTRAY_PASSWORD} -H "X-Bintray-Package:enmasse" -H "X-Bintray-Version:${VERSION}" -H "X-Bintray-Publish: 1" -H "X-Bintray-Override: 1" https://api.bintray.com/content/enmasse/${BINTRAY_DIR}/
curl -T mqtt-gateway/target/mqtt-gateway.jar -u ${BINTRAY_USER}:${BINTRAY_PASSWORD} -H "X-Bintray-Package:enmasse" -H "X-Bintray-Version:${VERSION}" -H "X-Bintray-Publish: 1" -H "X-Bintray-Override: 1" https://api.bintray.com/content/enmasse/${BINTRAY_DIR}/
curl -T mqtt-lwt/target/mqtt-lwt.jar -u ${BINTRAY_USER}:${BINTRAY_PASSWORD} -H "X-Bintray-Package:enmasse" -H "X-Bintray-Version:${VERSION}" -H "X-Bintray-Publish: 1" -H "X-Bintray-Override: 1" https://api.bintray.com/content/enmasse/${BINTRAY_DIR}/
curl -T none-authservice/build/none-authservice.tgz -u ${BINTRAY_USER}:${BINTRAY_PASSWORD} -H "X-Bintray-Package:enmasse" -H "X-Bintray-Version:${VERSION}" -H "X-Bintray-Publish: 1" -H "X-Bintray-Override: 1" https://api.bintray.com/content/enmasse/${BINTRAY_DIR}/
curl -T queue-scheduler/target/queue-scheduler.jar -u ${BINTRAY_USER}:${BINTRAY_PASSWORD} -H "X-Bintray-Package:enmasse" -H "X-Bintray-Version:${VERSION}" -H "X-Bintray-Publish: 1" -H "X-Bintray-Override: 1" https://api.bintray.com/content/enmasse/${BINTRAY_DIR}/
curl -T router/build/router.tgz -u ${BINTRAY_USER}:${BINTRAY_PASSWORD} -H "X-Bintray-Package:enmasse" -H "X-Bintray-Version:${VERSION}" -H "X-Bintray-Publish: 1" -H "X-Bintray-Override: 1" https://api.bintray.com/content/enmasse/${BINTRAY_DIR}/
curl -T ragent/build/ragent.tgz -u ${BINTRAY_USER}:${BINTRAY_PASSWORD} -H "X-Bintray-Package:enmasse" -H "X-Bintray-Version:${VERSION}" -H "X-Bintray-Publish: 1" -H "X-Bintray-Override: 1" https://api.bintray.com/content/enmasse/${BINTRAY_DIR}/
curl -T router-metrics/router-metrics.tgz -u ${BINTRAY_USER}:${BINTRAY_PASSWORD} -H "X-Bintray-Package:enmasse" -H "X-Bintray-Version:${VERSION}" -H "X-Bintray-Publish: 1" -H "X-Bintray-Override: 1" https://api.bintray.com/content/enmasse/${BINTRAY_DIR}/
curl -T subserv/build/subserv.tgz -u ${BINTRAY_USER}:${BINTRAY_PASSWORD} -H "X-Bintray-Package:enmasse" -H "X-Bintray-Version:${VERSION}" -H "X-Bintray-Publish: 1" -H "X-Bintray-Override: 1" https://api.bintray.com/content/enmasse/${BINTRAY_DIR}/
curl -T topic-forwarder/target/topic-forwarder.jar -u ${BINTRAY_USER}:${BINTRAY_PASSWORD} -H "X-Bintray-Package:enmasse" -H "X-Bintray-Version:${VERSION}" -H "X-Bintray-Publish: 1" -H "X-Bintray-Override: 1" https://api.bintray.com/content/enmasse/${BINTRAY_DIR}/
