include ../Makefile.common

build:
	@echo "Nothing to build"

package:
	tar -czf router.tgz run_qdr.sh qdrouterd.conf.template colocated-topic.snippet subscriptions.snippet amqp-kafka-bridge.snippet

