apiVersion: v1
kind: PersistentVolume
metadata:
    name: sasldb
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Recycle
    hostPath:
        path: /tmp/sasldb/
